spring:
  application:
    name: lovefinder-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    store-type: none
  #数据库配置
  datasource:
    driver-class-name: ${lf.datasource.driver-class-name}
    url: jdbc:mysql://${lf.datasource.host}:${lf.datasource.port}/${lf.datasource.database}
    username: ${lf.datasource.username}
    password: ${lf.datasource.password}
server:
  port: 8103
  servlet:
    context-path: /api
    # session 失效时间 1 天
    session:
      timeout: 86400
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）